import type { Metadata } from 'next';
import { Locale, dir } from '@/dictionary';
import '@/ui/globals.css';

export const metadata: Metadata = {
  title: 'ZeroLimit FrontEnd Sample',
  description: 'Generated by PeymanNaderi',
};

export default function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html
      lang={params.lang}
      dir={dir[params.lang]}>
      <body>{children}</body>
    </html>
  );
}
